# Generated by Django 6.0.7 on 2026-07-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterField(
            model_name='about',
            name='about_discription',
            field=models.TextField(max_length=255),
        ),
    ]
